"""
Agent Messages Schema
Message types that agents use to communicate within the LangGraph workflow
"""

from typing import Optional, List, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class AgentMessage:
    """Base message structure for all agent communications"""
    agent_name: str
    message_type: str
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    content: Dict[str, Any] = field(default_factory=dict)
    confidence_score: Optional[float] = None
    is_error: bool = False
    error_details: Optional[str] = None


@dataclass
class ResearchQuery:
    """Query structure for research agents"""
    drug_name: str
    indication: str
    query_type: str
    additional_filters: Dict[str, Any] = field(default_factory=dict)
    max_results: int = 10


@dataclass
class ResearchResult:
    """Result from research agent"""
    query: ResearchQuery
    total_results_found: int = 0
    results: List[Dict[str, Any]] = field(default_factory=list)
    summary: str = ""
    data_quality_score: Optional[float] = None
    limitations: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class AnalysisRequest:
    """Request for analysis from one agent to another"""
    requesting_agent: str
    target_agent: str
    analysis_type: str
    input_data: Dict[str, Any] = field(default_factory=dict)
    analysis_context: str = ""


@dataclass
class AnalysisResult:
    """Result from analysis agent"""
    analysis_type: str
    analyzed_by: str
    key_findings: List[str] = field(default_factory=list)
    detailed_analysis: Dict[str, Any] = field(default_factory=dict)
    confidence_level: Optional[float] = None
    recommendations: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class SynthesisRequest:
    """Request for synthesis/aggregation from multiple data sources"""
    synthesis_type: str
    input_sources: List[str] = field(default_factory=list)
    data_to_synthesize: Dict[str, Any] = field(default_factory=dict)
    synthesis_instructions: str = ""


@dataclass
class SynthesisResult:
    """Synthesized result combining multiple inputs"""
    synthesis_type: str
    synthesized_by: str
    integrated_insights: List[str] = field(default_factory=list)
    synthesis_output: Dict[str, Any] = field(default_factory=dict)
    data_sources_used: List[str] = field(default_factory=list)
    methodology: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class WorkflowProgressUpdate:
    """Progress update for the entire workflow"""
    current_phase: str
    agents_completed: List[str] = field(default_factory=list)
    agents_in_progress: List[str] = field(default_factory=list)
    agents_pending: List[str] = field(default_factory=list)
    overall_progress_percentage: int = 0
    estimated_time_remaining_seconds: Optional[int] = None
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class WorkflowError:
    """Error that occurred during workflow execution"""
    error_type: str
    agent_name: str
    error_message: str
    error_details: Dict[str, Any] = field(default_factory=dict)
    is_recoverable: bool = False
    recovery_action: Optional[str] = None
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ValidationResult:
    """Result of validation"""
    is_valid: bool
    validation_errors: List[str] = field(default_factory=list)
    validation_warnings: List[str] = field(default_factory=list)
    corrected_data: Optional[Dict[str, Any]] = None
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class AIGeneratedContent:
    """Content generated by an LLM within an agent"""
    content_type: str
    generated_by_agent: str
    raw_content: str
    structured_content: Dict[str, Any] = field(default_factory=dict)
    model_used: str = ""
    tokens_used: Optional[int] = None
    generation_confidence: Optional[float] = None
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


# Message routing constants
MESSAGE_TYPES = {
    "RESEARCH_COMPLETE": "research_complete",
    "ANALYSIS_COMPLETE": "analysis_complete",
    "SYNTHESIS_COMPLETE": "synthesis_complete",
    "ERROR_OCCURRED": "error_occurred",
    "READY_FOR_NEXT": "ready_for_next",
    "VALIDATION_FAILED": "validation_failed",
    "VALIDATION_PASSED": "validation_passed",
    "PROGRESS_UPDATE": "progress_update",
}


def create_agent_message(
    agent_name: str,
    message_type: str,
    content: Dict[str, Any],
    confidence_score: Optional[float] = None,
    is_error: bool = False,
    error_details: Optional[str] = None,
) -> AgentMessage:
    """Factory function to create agent messages"""
    return AgentMessage(
        agent_name=agent_name,
        message_type=message_type,
        content=content,
        confidence_score=confidence_score,
        is_error=is_error,
        error_details=error_details,
    )